http { 
	server {
		listen [::]:80 40.121.201.10; 
		server_name 40.121.201.10 
	} 
	location / { 
		root /usr/share/nginx/html; 
		index welcome.py; 
		autoindex on; 

	}

    # To run Python scripts, you would need to integrate FastCGI or uWSGI.
}

